version: '3.8'

services:
  lime-api:
    build: .
    ports:
      - "9090:9090"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - some-net

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    networks:
      - some-net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - some-net

networks:
  some-net:
    driver: bridge